### ISSUE TITLE
Error instantiating bean of type  [com.td.DatabaseBean]

### ISSUE THREAD

**Issue by tantan19960505** [jacaetevha/micronaut-jdbc-commons-dbcp2-configuration-failure#1]
public class Application {

    public static void main(String[] args) {
        ApplicationContext run = Micronaut.run(Application.class);
        System.out.println( BeanContext.run().getBean(DatabaseBean.class) ); //error
        System.out.println( run.getBean(DatabaseBean.class).dataSource ); //ok
    }
}

**Comment by jacaetevha** [comment]
Yes, thank you. My question was answered some time ago, and I forgot to delete this repo.
